sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t djangob1/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true djangob1/docker-react npm run test